#!/bin/bash

source $OPENSHIFT_HOMEDIR/python/virtenv/bin/activate

echo -e "Creating project"
cd $OPENSHIFT_REPO_DIR

django-admin startproject openshift

echo -e "Creating the database"

cd openshift
./manage migrate
